# Generated by Django 4.2 on 2023-10-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petalas_app', '0003_alter_crianca_entrada_alter_crianca_nascimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crianca',
        ),
    ]
