# Generated by Django 4.2 on 2023-10-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petalas_app', '0004_delete_crianca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id_crianca', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('nascimento', models.DateField()),
                ('status', models.TextField(max_length=255)),
                ('periodo', models.TextField(max_length=255)),
                ('entrada', models.DateField()),
                ('permanencia', models.TextField(max_length=255)),
                ('turma', models.TextField(max_length=255)),
                ('autoavaliacao', models.TextField(max_length=255)),
                ('faltas', models.IntegerField()),
            ],
        ),
    ]
