# Generated by Django 4.2.5 on 2023-11-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petalas_app', '0006_doacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id_presenca', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('turma', models.TextField(max_length=255)),
                ('presentes', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='faltas',
        ),
        migrations.AddField(
            model_name='doacao',
            name='cpf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
