# Generated by Django 4.2.5 on 2023-11-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petalas_app', '0009_remove_presenca_crianca_presenca_crianca_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='crianca_nome',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='presentes',
        ),
        migrations.AddField(
            model_name='presenca',
            name='presentes',
            field=models.ManyToManyField(related_name='presencas', to='petalas_app.crianca'),
        ),
    ]
