# Generated by Django 4.2.5 on 2023-11-30 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petalas_app', '0013_rename_descricao_doacao_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crianca',
            name='autoavaliacao',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='permanencia',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='status',
        ),
    ]
