# Generated by Django 4.2.5 on 2023-11-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petalas_app', '0014_remove_crianca_autoavaliacao_remove_crianca_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='cpf_crianca',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crianca',
            name='cpf_resp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crianca',
            name='email_resp',
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crianca',
            name='nome_resp',
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crianca',
            name='tel_resp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
